controller_list:
  - name: fake_west_robot_eax_controller
    type: $(arg fake_execution_type)
    joints:
      - west_joint_e1
      - west_joint_a1
      - west_joint_a2
      - west_joint_a3
      - west_joint_a4
      - west_joint_a5
      - west_joint_a6
  - name: fake_west_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - west_joint_a1
      - west_joint_a2
      - west_joint_a3
      - west_joint_a4
      - west_joint_a5
      - west_joint_a6
initial:  # Define initial robot poses per group
  - group: west_robot_eax
    pose: west_robot_eax_home_0