controller_joint_names:
    - east_joint_e1
    - east_joint_a1
    - east_joint_a2
    - east_joint_a3
    - east_joint_a4
    - east_joint_a5
    - east_joint_a6
#Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 10

# Joint trajectory controller
position_trajectory_controller:
  type: "position_controllers/JointGroupPositionController"
  joints:
    - east_joint_e1
    - east_joint_a1
    - east_joint_a2
    - east_joint_a3
    - east_joint_a4
    - east_joint_a5
    - east_joint_a6
    
# Joint trajectory controller
robot_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - east_joint_e1
    - east_joint_a1
    - east_joint_a2
    - east_joint_a3
    - east_joint_a4
    - east_joint_a5
    - east_joint_a6

  #state_publish_rate: 50 # Defaults to 50
  #action_monitor_rate: 20 # Defaults to 20

controller_list:
  - name: "/move_group/robot_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: 
    - east_joint_e1
    - east_joint_a1
    - east_joint_a2
    - east_joint_a3
    - east_joint_a4
    - east_joint_a5
    - east_joint_a6

Robot_IP: "192.168.1.201"
Robot_Port: 7000
