#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
URDF_DIR="${WORKSPACE_DIR}/robot_description/rccn_kuka_robot_cell/urdf"

if [[ ! -d "${URDF_DIR}" ]]; then
  echo "URDF directory not found: ${URDF_DIR}" >&2
  exit 1
fi

# Source ROS (avoid 'set -u' issues inside setup.bash)
source_ros() {
  local distro="$1"
  local setup="/opt/ros/${distro}/setup.bash"
  if [[ -f "${setup}" ]]; then
    set +u
    # shellcheck disable=SC1090
    source "${setup}"
    set -u
    return 0
  fi
  return 1
}

if [[ -n "${ROS_DISTRO:-}" ]]; then
  source_ros "${ROS_DISTRO}" || true
else
  source_ros humble || source_ros jazzy || true
fi

# Source this workspace overlay if present (needed for source-only deps like kuka_kr300_support)
if [[ -f "${WORKSPACE_DIR}/install/setup.bash" ]]; then
  set +u
  # shellcheck disable=SC1090
  source "${WORKSPACE_DIR}/install/setup.bash"
  set -u
fi

cd "${URDF_DIR}"

# Run from inside the urdf directory so xacro's autogenerated header is short
# (it records the input path exactly as provided).
ros2 run xacro xacro -o rccn_kuka_robot_cell.urdf rccn_kuka_robot_cell.xacro
ros2 run xacro xacro -o rccn_west_robot.urdf rccn_west_robot.xacro
ros2 run xacro xacro -o rccn_east_robot.urdf rccn_east_robot.xacro

echo "Updated URDFs in ${URDF_DIR}"